#ifndef GPIO_H__
#define GPIO_H__

// This file is autogenerated from `gpio.csv'. Do not edit, your changes will be lost!

// Pin Assignments for Arduino Mega2560, project: <none>.
enum {
    // Bus
    GPIO_PIN_RS485_TXD = 1,                        // RS485 TX
    GPIO_PIN_RS485_RXD = 0,                        // RS485 RX
    GPIO_PIN_ATN = 2,                              // Pulse high to signal ATN low on bus.
    GPIO_PIN_RS485_TX_EN = A0,                     // Enable RS485 xmitter
    GPIO_PIN_VOLTS_MON_BUS = A7,                   // Monitor volts on bus

    // Spare
    GPIO_PIN_SP_0 = 3,                             // Spare for debugging
    GPIO_PIN_SP_1 = 4,                             // Spare for debugging
    GPIO_PIN_SP_2 = 5,                             // Spare for debugging
    GPIO_PIN_SP_3 = 6,                             // Spare for debugging
    GPIO_PIN_SP_4 = 7,                             // Spare for debugging
    GPIO_PIN_SP_5 = A4,                            // Spare for debugging
    GPIO_PIN_SP_6 = A5,                            // Spare for debugging

    // Console
    GPIO_PIN_CONS_RX = 8,                          // console serial data in
    GPIO_PIN_CONS_TX = 9,                          // console serial data out

    // SPI
    GPIO_PIN_SSEL = 10,                            // SPI slave select to Accelerometer
    GPIO_PIN_MOSI = 11,                            // SPI to Accelerometer
    GPIO_PIN_MISO = 12,                            // SPI to Accelerometer
    GPIO_PIN_SCK = 13,                             // SPI to Accelerometer

    // Misc
    GPIO_PIN_LED = A1,                             // Blinky LED
    GPIO_PIN_SEL0 = A2,                            // Address select, link to 0V.
    GPIO_PIN_SEL1 = A3,                            // Address select, link to 0V.
};
// Extra symbols from symbol directive.
#define GPIO_SERIAL_RS485 Serial // Serial port for RS485.


// Direct access ports.

// SP_0: Spare for debugging
static inline void gpioSp0SetModeOutput() { DDRD |= _BV(3); }
static inline void gpioSp0SetModeInput() { DDRD &= ~_BV(3); }
static inline void gpioSp0SetMode(bool fout) { if (fout) DDRD |= _BV(3); else DDRD &= ~_BV(3); }
static inline bool gpioSp0Read() { return PIND | _BV(3); }
static inline void gpioSp0Toggle() { PORTD ^= _BV(3); }
static inline void gpioSp0Set() { PORTD |= _BV(3); }
static inline void gpioSp0Clear() { PORTD &= ~_BV(3); }
static inline void gpioSp0Write(bool b) { if (b) PORTD |= _BV(3); else PORTD &= ~_BV(3); }

// SP_1: Spare for debugging
static inline void gpioSp1SetModeOutput() { DDRD |= _BV(4); }
static inline void gpioSp1SetModeInput() { DDRD &= ~_BV(4); }
static inline void gpioSp1SetMode(bool fout) { if (fout) DDRD |= _BV(4); else DDRD &= ~_BV(4); }
static inline bool gpioSp1Read() { return PIND | _BV(4); }
static inline void gpioSp1Toggle() { PORTD ^= _BV(4); }
static inline void gpioSp1Set() { PORTD |= _BV(4); }
static inline void gpioSp1Clear() { PORTD &= ~_BV(4); }
static inline void gpioSp1Write(bool b) { if (b) PORTD |= _BV(4); else PORTD &= ~_BV(4); }

// SP_2: Spare for debugging
static inline void gpioSp2SetModeOutput() { DDRD |= _BV(5); }
static inline void gpioSp2SetModeInput() { DDRD &= ~_BV(5); }
static inline void gpioSp2SetMode(bool fout) { if (fout) DDRD |= _BV(5); else DDRD &= ~_BV(5); }
static inline bool gpioSp2Read() { return PIND | _BV(5); }
static inline void gpioSp2Toggle() { PORTD ^= _BV(5); }
static inline void gpioSp2Set() { PORTD |= _BV(5); }
static inline void gpioSp2Clear() { PORTD &= ~_BV(5); }
static inline void gpioSp2Write(bool b) { if (b) PORTD |= _BV(5); else PORTD &= ~_BV(5); }

// SP_3: Spare for debugging
static inline void gpioSp3SetModeOutput() { DDRD |= _BV(6); }
static inline void gpioSp3SetModeInput() { DDRD &= ~_BV(6); }
static inline void gpioSp3SetMode(bool fout) { if (fout) DDRD |= _BV(6); else DDRD &= ~_BV(6); }
static inline bool gpioSp3Read() { return PIND | _BV(6); }
static inline void gpioSp3Toggle() { PORTD ^= _BV(6); }
static inline void gpioSp3Set() { PORTD |= _BV(6); }
static inline void gpioSp3Clear() { PORTD &= ~_BV(6); }
static inline void gpioSp3Write(bool b) { if (b) PORTD |= _BV(6); else PORTD &= ~_BV(6); }

// SP_4: Spare for debugging
static inline void gpioSp4SetModeOutput() { DDRD |= _BV(7); }
static inline void gpioSp4SetModeInput() { DDRD &= ~_BV(7); }
static inline void gpioSp4SetMode(bool fout) { if (fout) DDRD |= _BV(7); else DDRD &= ~_BV(7); }
static inline bool gpioSp4Read() { return PIND | _BV(7); }
static inline void gpioSp4Toggle() { PORTD ^= _BV(7); }
static inline void gpioSp4Set() { PORTD |= _BV(7); }
static inline void gpioSp4Clear() { PORTD &= ~_BV(7); }
static inline void gpioSp4Write(bool b) { if (b) PORTD |= _BV(7); else PORTD &= ~_BV(7); }

// LED: Blinky LED
static inline void gpioLedSetModeOutput() { DDRC |= _BV(1); }
static inline void gpioLedSetModeInput() { DDRC &= ~_BV(1); }
static inline void gpioLedSetMode(bool fout) { if (fout) DDRC |= _BV(1); else DDRC &= ~_BV(1); }
static inline bool gpioLedRead() { return PINC | _BV(1); }
static inline void gpioLedToggle() { PORTC ^= _BV(1); }
static inline void gpioLedSet() { PORTC |= _BV(1); }
static inline void gpioLedClear() { PORTC &= ~_BV(1); }
static inline void gpioLedWrite(bool b) { if (b) PORTC |= _BV(1); else PORTC &= ~_BV(1); }

// SP_5: Spare for debugging
static inline void gpioSp5SetModeOutput() { DDRC |= _BV(4); }
static inline void gpioSp5SetModeInput() { DDRC &= ~_BV(4); }
static inline void gpioSp5SetMode(bool fout) { if (fout) DDRC |= _BV(4); else DDRC &= ~_BV(4); }
static inline bool gpioSp5Read() { return PINC | _BV(4); }
static inline void gpioSp5Toggle() { PORTC ^= _BV(4); }
static inline void gpioSp5Set() { PORTC |= _BV(4); }
static inline void gpioSp5Clear() { PORTC &= ~_BV(4); }
static inline void gpioSp5Write(bool b) { if (b) PORTC |= _BV(4); else PORTC &= ~_BV(4); }

// SP_6: Spare for debugging
static inline void gpioSp6SetModeOutput() { DDRC |= _BV(5); }
static inline void gpioSp6SetModeInput() { DDRC &= ~_BV(5); }
static inline void gpioSp6SetMode(bool fout) { if (fout) DDRC |= _BV(5); else DDRC &= ~_BV(5); }
static inline bool gpioSp6Read() { return PINC | _BV(5); }
static inline void gpioSp6Toggle() { PORTC ^= _BV(5); }
static inline void gpioSp6Set() { PORTC |= _BV(5); }
static inline void gpioSp6Clear() { PORTC &= ~_BV(5); }
static inline void gpioSp6Write(bool b) { if (b) PORTC |= _BV(5); else PORTC &= ~_BV(5); }

#endif   // GPIO_H__
