#ifndef IRMP_SUPPORT_SIRCS_PROTOCOL
 #define IRMP_SUPPORT_SIRCS_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NEC_PROTOCOL
 #define IRMP_SUPPORT_NEC_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_SAMSUNG_PROTOCOL
 #define IRMP_SUPPORT_SAMSUNG_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_KASEIKYO_PROTOCOL
 #define IRMP_SUPPORT_KASEIKYO_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_JVC_PROTOCOL
 #define IRMP_SUPPORT_JVC_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NEC16_PROTOCOL
 #define IRMP_SUPPORT_NEC16_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NEC42_PROTOCOL
 #define IRMP_SUPPORT_NEC42_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_MATSUSHITA_PROTOCOL
 #define IRMP_SUPPORT_MATSUSHITA_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_DENON_PROTOCOL
 #define IRMP_SUPPORT_DENON_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RC5_PROTOCOL
 #define IRMP_SUPPORT_RC5_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RC6_PROTOCOL
 #define IRMP_SUPPORT_RC6_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_IR60_PROTOCOL
 #define IRMP_SUPPORT_IR60_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_GRUNDIG_PROTOCOL
 #define IRMP_SUPPORT_GRUNDIG_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_SIEMENS_PROTOCOL
 #define IRMP_SUPPORT_SIEMENS_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NOKIA_PROTOCOL
 #define IRMP_SUPPORT_NOKIA_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_BOSE_PROTOCOL
 #define IRMP_SUPPORT_BOSE_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_KATHREIN_PROTOCOL
 #define IRMP_SUPPORT_KATHREIN_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NUBERT_PROTOCOL
 #define IRMP_SUPPORT_NUBERT_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_FAN_PROTOCOL
 #define IRMP_SUPPORT_FAN_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_SPEAKER_PROTOCOL
 #define IRMP_SUPPORT_SPEAKER_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_BANG_OLUFSEN_PROTOCOL
 #define IRMP_SUPPORT_BANG_OLUFSEN_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RECS80_PROTOCOL
 #define IRMP_SUPPORT_RECS80_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RECS80EXT_PROTOCOL
 #define IRMP_SUPPORT_RECS80EXT_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_THOMSON_PROTOCOL
 #define IRMP_SUPPORT_THOMSON_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NIKON_PROTOCOL
 #define IRMP_SUPPORT_NIKON_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_NETBOX_PROTOCOL
 #define IRMP_SUPPORT_NETBOX_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_ORTEK_PROTOCOL
 #define IRMP_SUPPORT_ORTEK_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_TELEFUNKEN_PROTOCOL
 #define IRMP_SUPPORT_TELEFUNKEN_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_FDC_PROTOCOL
 #define IRMP_SUPPORT_FDC_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RCCAR_PROTOCOL
 #define IRMP_SUPPORT_RCCAR_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_ROOMBA_PROTOCOL
 #define IRMP_SUPPORT_ROOMBA_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RUWIDO_PROTOCOL
 #define IRMP_SUPPORT_RUWIDO_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_A1TVBOX_PROTOCOL
 #define IRMP_SUPPORT_A1TVBOX_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_LEGO_PROTOCOL
 #define IRMP_SUPPORT_LEGO_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RCMM_PROTOCOL
 #define IRMP_SUPPORT_RCMM_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_LGAIR_PROTOCOL
 #define IRMP_SUPPORT_LGAIR_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_SAMSUNG48_PROTOCOL
 #define IRMP_SUPPORT_SAMSUNG48_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_MERLIN_PROTOCOL
 #define IRMP_SUPPORT_MERLIN_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_PENTAX_PROTOCOL
 #define IRMP_SUPPORT_PENTAX_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_S100_PROTOCOL
 #define IRMP_SUPPORT_S100_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_ACP24_PROTOCOL
 #define IRMP_SUPPORT_ACP24_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_TECHNICS_PROTOCOL
 #define IRMP_SUPPORT_TECHNICS_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_PANASONIC_PROTOCOL
 #define IRMP_SUPPORT_PANASONIC_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_MITSU_HEAVY_PROTOCOL
 #define IRMP_SUPPORT_MITSU_HEAVY_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_VINCENT_PROTOCOL
 #define IRMP_SUPPORT_VINCENT_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_SAMSUNGAH_PROTOCOL
 #define IRMP_SUPPORT_SAMSUNGAH_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_IRMP16_PROTOCOL
 #define IRMP_SUPPORT_IRMP16_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_GREE_PROTOCOL
 #define IRMP_SUPPORT_GREE_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RCII_PROTOCOL
 #define IRMP_SUPPORT_RCII_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_METZ_PROTOCOL
 #define IRMP_SUPPORT_METZ_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_MELINERA_PROTOCOL
 #define IRMP_SUPPORT_MELINERA_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RF_GEN24_PROTOCOL
 #define IRMP_SUPPORT_RF_GEN24_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RF_X10_PROTOCOL
 #define IRMP_SUPPORT_RF_X10_PROTOCOL 0
#endif
#ifndef IRMP_SUPPORT_RF_MEDION_PROTOCOL
 #define IRMP_SUPPORT_RF_MEDION_PROTOCOL 0
#endif

#ifndef IRMP_PROTOCOL_NAMES
 #define IRMP_PROTOCOL_NAMES 0
#endif
#ifndef IRSND_PROTOCOL_NAMES
 #define IRSND_PROTOCOL_NAMES 0
#endif
