#ifndef GPIO_H__
#define GPIO_H__

// This file is autogenerated from `gpio.csv'.

// Pin Assignments for Arduino Pro Mini
enum {
    // Bus
    GPIO_PIN_RS485_TXD = 1,                        // RS485 TX
    GPIO_PIN_RS485_RXD = 0,                        // RS485 RX
    GPIO_PIN_ATN = 2,                              // Pulse high to signal ATN low on bus.
    GPIO_PIN_RS485_TX_EN = A0,                     // Enable RS485 xmitter
    GPIO_PIN_VOLTS_MON_BUS = A7,                   // Monitor volts on bus

    // Console
    GPIO_PIN_CONS_TX = 7,                          // console serial data out
    GPIO_PIN_CONS_RX = 8,                          // console serial data in

    // Spare
    GPIO_PIN_SPARE_1 = 9,                          // Spare for debugging
    GPIO_PIN_SPARE_2 = A2,                         // Spare for debugging
    GPIO_PIN_SPARE_3 = A3,                         // Spare for debugging

    // Misc
    GPIO_PIN_LED = A1,                             // Blinky LED
};

// Direct access ports.

// SPARE_1: Spare for debugging
static inline void gpioSpare1SetModeOutput() { DDRB |= _BV(1); }
static inline void gpioSpare1SetModeInput() { DDRB &= ~_BV(1); }
static inline void gpioSpare1SetMode(bool fout) { if (fout) DDRB |= _BV(1); else DDRB &= ~_BV(1); }
static inline bool gpioSpare1Read() { return PINB | _BV(1); }
static inline void gpioSpare1Toggle() { PORTB ^= _BV(1); }
static inline void gpioSpare1Set() { PORTB |= _BV(1); }
static inline void gpioSpare1Clear() { PORTB &= ~_BV(1); }
static inline void gpioSpare1Write(bool b) { if (b) PORTB |= _BV(1); else PORTB &= ~_BV(1); }

// LED: Blinky LED
static inline void gpioLedSetModeOutput() { DDRC |= _BV(1); }
static inline void gpioLedSetModeInput() { DDRC &= ~_BV(1); }
static inline void gpioLedSetMode(bool fout) { if (fout) DDRC |= _BV(1); else DDRC &= ~_BV(1); }
static inline bool gpioLedRead() { return PINC | _BV(1); }
static inline void gpioLedToggle() { PORTC ^= _BV(1); }
static inline void gpioLedSet() { PORTC |= _BV(1); }
static inline void gpioLedClear() { PORTC &= ~_BV(1); }
static inline void gpioLedWrite(bool b) { if (b) PORTC |= _BV(1); else PORTC &= ~_BV(1); }

// SPARE_2: Spare for debugging
static inline void gpioSpare2SetModeOutput() { DDRC |= _BV(2); }
static inline void gpioSpare2SetModeInput() { DDRC &= ~_BV(2); }
static inline void gpioSpare2SetMode(bool fout) { if (fout) DDRC |= _BV(2); else DDRC &= ~_BV(2); }
static inline bool gpioSpare2Read() { return PINC | _BV(2); }
static inline void gpioSpare2Toggle() { PORTC ^= _BV(2); }
static inline void gpioSpare2Set() { PORTC |= _BV(2); }
static inline void gpioSpare2Clear() { PORTC &= ~_BV(2); }
static inline void gpioSpare2Write(bool b) { if (b) PORTC |= _BV(2); else PORTC &= ~_BV(2); }

// SPARE_3: Spare for debugging
static inline void gpioSpare3SetModeOutput() { DDRC |= _BV(3); }
static inline void gpioSpare3SetModeInput() { DDRC &= ~_BV(3); }
static inline void gpioSpare3SetMode(bool fout) { if (fout) DDRC |= _BV(3); else DDRC &= ~_BV(3); }
static inline bool gpioSpare3Read() { return PINC | _BV(3); }
static inline void gpioSpare3Toggle() { PORTC ^= _BV(3); }
static inline void gpioSpare3Set() { PORTC |= _BV(3); }
static inline void gpioSpare3Clear() { PORTC &= ~_BV(3); }
static inline void gpioSpare3Write(bool b) { if (b) PORTC |= _BV(3); else PORTC &= ~_BV(3); }

#endif   // GPIO_H__
