#ifndef GPIO_LOCAL_H__
#define GPIO_LOCAL_H__

// This file is autogenerated from `gpio.csv'.

// Pin Assignments for Arduino Pro Mini
enum {   
	/* Bus */
	GPIO_PIN_RS485_TXD = 1,                         /* RS485 TX */
	GPIO_PIN_RS485_RXD = 0,                         /* RS485 RX */
	GPIO_PIN_ATN = 2,                               /* Pulse high to signal ATN low on bus. */
	GPIO_PIN_RS485_TX_EN = A0,                      /* Enable RS485 xmitter */
	GPIO_PIN_VOLTS_MON_BUS = A7,                    /* Monitor volts on bus */

	/* Spare */
	GPIO_PIN_ = 3,                                  
	GPIO_PIN_ = 4,                                  
	GPIO_PIN_ = 5,                                  
	GPIO_PIN_ = 6,                                  
	GPIO_PIN_ = 7,                                  
	GPIO_PIN_ = A4,                                 
	GPIO_PIN_ = A5,                                 
	GPIO_PIN_ = A6,                                 /* Tie to ground as unused. */

	/* Console */
	GPIO_PIN_CONS_TX = 8,                           /* Console serial data out. */
	GPIO_PIN_CONS_RX = 9,                           /* Console serial data in. */

	/* SPI */
	GPIO_PIN_SSEL = 10,                             /* SPI slave select to Accelerometer */
	GPIO_PIN_MOSI = 11,                             /* SPI to Accelerometer */
	GPIO_PIN_MISO = 12,                             /* SPI to Accelerometer */
	GPIO_PIN_SCK = 13,                              /* SPI to Accelerometer */

	/* Misc */
	GPIO_PIN_LED = A1,                              /* Blinky LED */
	GPIO_PIN_SEL0 = A2,                             /* Address select, link to 0V. */
	GPIO_PIN_SEL1 = A3,                             /* Address select, link to 0V. */

};

// Direct access ports.	
GPIO_DECLARE_PIN_ACCESS_FUNCS(Led, C, 1)        /* Blinky LED */


#define GPIO_UNUSED_PINS 3, 4, 5, 6, 7, A4, A5, A6

#endif		// GPIO_LOCAL_H__