/* This file is autogenerated by grm -- do not edit. */

#ifndef UNITY_INCLUDE_CONFIG_H
#error "Must define UNITY_INCLUDE_CONFIG_H."
#endif

/*** Standard includes. ***/
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

#include "unity.h"


/*** Stuff copied from test files (should be #include's, declarations & macros only) ***/
#include "buffer.h"

/*** External test functions scraped from test files. ***/
void testBufferInit();
void testBufferAddChar();
void testBufferAddCharFull();
void testBufferAddCharOverflow();
void testBufferReset();

/*** Fixture & dump functions from test files. ***/
/* None */

/* Declare test stubs. */


/*** Extra Unity support. ***/

/* Functions for setup, diagnostics dump on a test failure & teardown. */
typedef void (*fixture_func_t)(void);
static fixture_func_t setUp_func, dump_func, tearDown_func;
void registerFixture(fixture_func_t setup, fixture_func_t dumper, fixture_func_t teardown) {
	setUp_func = setup;
	dump_func = dumper;
	tearDown_func = teardown;
}

void setUp() { if (setUp_func) setUp_func(); }
void dumpTestContext() { if (dump_func) dump_func(); }
void tearDown() { if (tearDown_func) tearDown_func(); }

static void do_run_test(UnityTestFunction func, const char* name, int line_num) {
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
	UnityDefaultTestRun(func, name, line_num);
}

int main(int argc, char** argv) {
/*
	int rc_parse = UnityParseOptions(argc,argv);
	if (rc_parse != 0)
		return rc_parse;
*/
  UnityBegin("");
  
  UnitySetTestFile("..\test_buffer.cpp");
  do_run_test(testBufferInit, "testBufferInit", 11);
  do_run_test(testBufferAddChar, "testBufferAddChar", 20);
  do_run_test(testBufferAddCharFull, "testBufferAddCharFull", 30);
  do_run_test(testBufferAddCharOverflow, "testBufferAddCharOverflow", 41);
  do_run_test(testBufferReset, "testBufferReset", 53);

  return UnityEnd();
}

/*

*/
